### ISSUE TITLE
Destruction of the global Parallel2d object causes a crash on exit

### ISSUE THREAD

**Issue by valkenburg** [daverio/LATfield2#1]
If I compile this empty program, with the latfield header, it crashes:

```
#include "LATfield2.hpp"

int main (int argc, char ** argv ) {
  parallel.initialize(1, 1);

  std::cout << "Hello and goodbye world.\n";
  return 0;
}
```

output:

```
./test.out
Hello and goodbye world.
[macth83:15594] *** Process received signal ***
[macth83:15594] Signal: Segmentation fault: 11 (11)
[macth83:15594] Signal code:  (0)
[macth83:15594] Failing at address: 0x0
[macth83:15594] [ 0] 0   libsystem_platform.dylib            0x00007fff9c5f0eaa _sigtramp + 26
[macth83:15594] [ 1] 0   ???                                 0x0000000000000000 0x0 + 0
[macth83:15594] [ 2] 0   test.out                            0x0000000100f6170c _ZN10Parallel2dD1Ev + 28
[macth83:15594] [ 3] 0   libsystem_c.dylib                   0x00007fff8d25846b __cxa_finalize_ranges + 345
[macth83:15594] [ 4] 0   libsystem_c.dylib                   0x00007fff8d25876f exit + 55
[macth83:15594] [ 5] 0   libdyld.dylib                       0x00007fffa087d5b4 start + 8
[macth83:15594] *** End of error message ***
Segmentation fault: 11
```

**Comment by JulianAdamek** [comment]
Hi Wessel,

I think the parallel class requires the process grid to be at least 2x2, 
i.e. it does not work with 1x1. Does the crash also occur with 
parallel.initialize(n,m), where n,m>1 ?

Best wishes,
Julian.

**Comment by valkenburg** [comment]
HI Julian,

thanks for the quick reply. I checked, and yes, all four processes have the same crash if I initialize with   parallel.initialize(2, 2); and run with mpirun -np 4  ./test.out.

Cheers,
Wessel

**Comment by JulianAdamek** [comment]
Hi Wessel,

you say the crash occurs at cleanup? We have seen this issue before, but 
it only occurs on some systems - are you running on a Mac by any chance? 
Maybe David can look into this.

Best wishes,
Julian.

**Comment by valkenburg** [comment]
Yes, it is on mac, and it happens both with gcc 5.2 and clang 7.0.2, although openmpi v1.8.6 is anyway compiled with clang.

**Comment by daverio** [comment]
Hi Wessel,

Sorry for the late reply. I have try to reproduce this error. I think it come from the line 690-691 of the parallel2d.hpp...

?Try to pull once to see if it was that.

David

?

---

De : Wessel Valkenburg notifications@github.com
Envoyé : mercredi 3 février 2016 17:27
À : daverio/LATfield2_particles
Objet : Re: [LATfield2_particles] Destruction of the global Parallel2d object causes a crash on exit (#1)

Yes, it is on mac, and it happens both with gcc 5.2 and clang 7.0.2, although openmpi v1.8.6 is anyway compiled with clang.

> On 03 Feb 2016, at 17:20, JulianAdamek notifications@github.com wrote:
> 
> Hi Wessel,
> 
> you say the crash occurs at cleanup? We have seen this issue before, but
> it only occurs on some systems - are you running on a Mac by any chance?
> Maybe David can look into this.
> 
> Best wishes,
> Julian.
> 
> On 02/03/2016 05:10 PM, Wessel Valkenburg wrote:
> 
> > HI Julian,
> > 
> > thanks for the quick reply. I checked, and yes, all four processes have
> > the same crash if I initialize with parallel.initialize(2, 2); and run
> > with mpirun -np 4 ./test.out.
> > 
> > Cheers,
> > Wessel
> > 
> > > On 03 Feb 2016, at 17:08, JulianAdamek notifications@github.com wrote:
> > > 
> > > Hi Wessel,
> > > 
> > > I think the parallel class requires the process grid to be at least 2x2,
> > > i.e. it does not work with 1x1. Does the crash also occur with
> > > parallel.initialize(n,m), where n,m>1 ?
> > > 
> > > Best wishes,
> > > Julian.
> > > 
> > > On 02/03/2016 05:03 PM, Wessel Valkenburg wrote:
> > > 
> > > > If I compile this empty program, with the latfield header, it crashes:
> > > > 
> > > > #include "LATfield2.hpp"
> > > > 
> > > > int main (int argc, char *\* argv ) {
> > > > parallel.initialize(1, 1);
> > > > 
> > > > std::cout << "Hello and goodbye world.\n";
> > > > return 0;
> > > > }
> > > > 
> > > > output:
> > > > 
> > > > ./test.out
> > > > Hello and goodbye world.
> > > > [macth83:15594] **\* Process received signal ***
> > > > [macth83:15594] Signal: Segmentation fault: 11 (11)
> > > > [macth83:15594] Signal code: (0)
> > > > [macth83:15594] Failing at address: 0x0
> > > > [macth83:15594] [ 0] 0 libsystem_platform.dylib 0x00007fff9c5f0eaa
> > > > _sigtramp + 26
> > > > [macth83:15594] [ 1] 0 ??? 0x0000000000000000 0x0 + 0
> > > > [macth83:15594] [ 2] 0 test.out 0x0000000100f6170c
> > > > _ZN10Parallel2dD1Ev + 28
> > > > [macth83:15594] [ 3] 0 libsystem_c.dylib 0x00007fff8d25846b
> > > > __cxa_finalize_ranges + 345
> > > > [macth83:15594] [ 4] 0 libsystem_c.dylib 0x00007fff8d25876f exit + 55
> > > > [macth83:15594] [ 5] 0 libdyld.dylib 0x00007fffa087d5b4 start + 8
> > > > [macth83:15594] **\* End of error message ***
> > > > Segmentation fault: 11
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/daverio/LATfield2_particles/issues/1.
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/daverio/LATfield2_particles/issues/1#issuecomment-179316261.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/daverio/LATfield2_particles/issues/1#issuecomment-179317094.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub https://github.com/daverio/LATfield2_particles/issues/1#issuecomment-179320623.

##

**Comment by valkenburg** [comment]
I found that the issue is not with LATField, but with open-mpi when compiled on OS X (with several recent versions up to and including 1.10.2), which crashes when MPI_Finalize() is called _after_ main() returns. (See [this issue I posted on the open-mpi repository.](https://github.com/open-mpi/ompi/issues/1364))

The solution for OS X users is to make sure that MPI_Finalize() is called inside the main function, hence before the destruction of the parallel object which would otherwise call MPI_Finalize() after main exits.

For example, this programme also gives the same crash:

```
#include "mpi.h"

class GlobalMPITest {
public:
  GlobalMPITest() { MPI::Init(); }
  ~GlobalMPITest() {
    if (! MPI::Is_finalized()) MPI::Finalize();
  }
};

GlobalMPITest test;

int main (int argc, char ** argv ) {

  std::cout << "Hello and goodbye world.\n";
  return 0;
}
```

**Comment by daverio** [comment]
?Great! thanks for the solution

---

De : Wessel Valkenburg notifications@github.com
Envoyé : lundi 15 février 2016 17:58
À : daverio/LATfield2_particles
Cc : David Daverio
Objet : Re: [LATfield2_particles] Destruction of the global Parallel2d object causes a crash on exit (#1)

I found that the issue is not with LATField, but with open-mpi when compiled on OS X (with several recent versions up to and including 1.10.2), which crashes when MPI_Finalize() is called after main() returns.

The solution for OS X users is to make sure that MPI_Finalize() is called inside the main function, hence before the destruction of the parallel object which would otherwise call MPI_Finalize() after main exits.

For example, this programme also gives the same crash:

`#include "mpi.h"

class GlobalMPITest {
public:
GlobalMPITest() { MPI::Init(); }
~GlobalMPITest() {
if (! MPI::Is_finalized()) MPI::Finalize();
}
};

GlobalMPITest test;

int main (int argc, char *\* argv ) {

std::cout << "Hello and goodbye world.\n";
return 0;
}
`

##
