### ISSUE TITLE
Suggestion: use enum classes

### ISSUE THREAD

**Issue by Lagrang3** [daverio/LATfield2#11]
In this library you can find global values like this
```
int symmetric = 1;
int unsymmetric = 0;
```
see [here](https://github.com/daverio/LATfield2/blob/5f21b631385f6e32f97f693d8259e34fa196e37a/LATfield2_Field.hpp#L16) for instance. 
These two for instance represent two possible types of field *symmetric* or *asymmetric*.
But they should be declared `const` since they are not meant for writing.

Furthermore their purpose is nicely handled by a C++ feature called `enum class`, see Stroustrup *The C++ Programming Language* section 8.4.1. *An enum class is a scoped and strongly typed enumeration.*
That means by writing:
```
enum class symmetry_t {
    symmetric, unsymmetric
};
```

1. you get them to be read only objects by default,
2. they do not clash with other names, `symmetric` and `unsymmetric` are within the scope `symmetry_t::` and not global,
3. you get type check at compile time,
4. you can have templated classes and functions on the `symmetry_t` type, for example:
```
template<symmetry_t>
class Field;
```

Some examples from the book read like this:
```
symmetry_t s1 = 7 ;// error: int->symmetry_t conversion
int s2 = symmetric; // error: symmetric is not in scope
int s3 = symmetry_t::symmetric; // error: no symmetry_t->int conversion
symmetry_t s4 = symmetry_t::symmetric; // OK
```

That is you field constructor
```
		Field(Lattice& lattice, int rows, int cols, int symmetry=unsymmetric);
```
could become 
```
		Field(Lattice& lattice, int rows, int cols, symmetry_t symmetry = symmetry_t::unsymmetric);
```
and from the user point of view you couldn't make
```
Field<Real> phi(lat,row,cols, 2 ); // error: int->symmetry_t conversion
```
which in any case is a God bless compiler error because who knows what `2` stands for?
Instead, the user is bound to type:
```
Field<Real> phi(lat,row,cols, symmetry_t::symmetric );
```

**Comment by daverio** [comment]
I definitely agree! Once again its a feature inherited from first version of latfield.
I would prefere a solution which allow : LATField2::symmetric, rather than a new classname. But indeed it might not be a bad idea, but it means that code using latfiled2 wont compile anymore and would need a fix... 

I will think about it, but indeed that would reduce potential bug really hard to find...

**Comment by daverio** [comment]
Once again backward compabilities prevent to do this
