### ISSUE TITLE
Lattice's default copy constructor

### ISSUE THREAD

**Issue by Lagrang3** [daverio/LATfield2#13]
Reading Latfield2's [paper](https://arxiv.org/abs/1508.05610) you will find on page 6 a code snippet
```
Field<double> phi(lat,comp);
```
suggesting to readers that Latfield provides an interface that allows object initialization upon construction. That's fine, this is one of features of C++ that C doesn't have.
On the other hand one of the examples provided in this repository shows that a complex lattice is initialized by calling the method `Lattice::initializeRealFFT`, see [here](https://github.com/daverio/LATfield2/blob/5f21b631385f6e32f97f693d8259e34fa196e37a/examples/fft.cpp#L56).

A user, like myself, might think that the dual lattice might as well be initialized upon construction, just like `Field` does, and can try the following code:
```
#include <iostream>
#define FFT3D
#include "LATfield2.hpp"

using LATfield2::Lattice;
int main()
{
    const int n=2,m=2;
    const int BoxSize = 64;
    const int dim =3;
    const int comp = 1;
    const int halo = 1;
    
    parallel.initialize(n,m);
    Lattice lat(dim,BoxSize,halo);
    
    Lattice latK(lat);
    //latK.initializeRealFFT(lat,halo);
    return 0;
}
```
which compiles. 
```
$ make
g++ main.cpp -I../.. `pkg-config --cflags --libs fftw3 ompi`
```

However, that code fails at runtime:
```
$ mpirun -np 4 a.out 
free(): double free detected in tcache 2
```

This happens because the developers didn't write a copy constructor for `Lattice`, and the C++ compiler did it automatically.
The fact is that some members of `Lattice` are raw pointers to allocated memory owned by an instance of `Lattice`.
Copy will lead to double freed memory and thus it should not be allowed!

**Comment by Lagrang3** [comment]
One example of a class in the standard library that has `deleted` its copy constructor and copy assignment is the `std::unique_ptr`,
see the [link](https://en.cppreference.com/w/cpp/memory/unique_ptr). In this case too there are resources that are *owned* by the object itself, and released on destruction, and therefore it cannot be copied.

The problem with the `Lattice` class can be resolved basically in two ways:

1. keep using raw pointers, `new[]` and `delete[]`, and manually delete the copy constructor and copy assignment or
2. remove all raw pointers, using instead data holding structures of the `std` like `std::vector`, or use smart pointers.

@daverio , @JulianAdamek What do you think?

I prefer the 2nd option, in this way we can be sure that memory is released and acquired without worries. 
But the fastest fix is number 1.

I will make a PR for fix 1 and in the future we'll make it number 2.

**Comment by daverio** [comment]
In some codes (not public) the copy and assignment constructors are used, so they are definitely needed.

Yes I definitely agree that smart pointer should be used to handle such things, but if you look at codes like gevolution, which is written in a C fashion, smart pointer would just be an additional layer of complication... Then in some case, for efficiency reasons, it is better to keep a local copy of the lattice class to increase data locality.

**Comment by Lagrang3** [comment]
> In some codes (not public) the copy and assignment constructors are used

Copy assignment and construction of `Lattice` leads to double freed memory on destruction.
I cannot imagine how could someone use this as a feature. That's why the fix removes it.
Could you please provide an example of such use, so I can learn this particular hack?
