### ISSUE TITLE
Global parallel variable

### ISSUE THREAD

**Issue by Lagrang3** [daverio/LATfield2#15]
LATfield cannot be used in a project with multiple translation units.
For instace consider this little project with the following files 

```
# makefile
EXE := hello
OBJS := main.o myfun.o
INCLUDE := -I../LATfield2 $(shell pkg-config --cflags ompi)
LIBS := $(shell pkg-config --libs ompi)

default: $(EXE)

$(EXE) : $(OBJS)
	c++ $(OBJS) -o $@ $(LIBS)

$(OBJS) : %.o : %.cpp
	c++ -c $^ $(INCLUDE) $(LIBS)

clean : 
	-rm $(OBJS) $(EXE)

.PHONY: clean default
```

```
// main.cpp
#include "myfun.hpp"
#include <mpi.h>
#include "LATfield2.hpp"

int main()
{
    parallel.initialize(2,2);
    hello();
    return 0;
}
```

```
// myfun.hpp
#pragma once

void hello();
```

```
// myfun.cpp
#include "myfun.hpp"
#include <iostream>
#include "LATfield2.hpp"

void hello()
{
    std::cout << "Hello\n";
}
```

If the line `#include "LATfield2.hpp"` is commented in the `myfun.cpp` the project compiles. Otherwise you get a linker error:
```
/usr/bin/ld: myfun.o: in function `Parallel2d::Parallel2d()':
myfun.cpp:(.text+0x0): multiple definition of `Parallel2d::Parallel2d()'; main.o:main.cpp:(.text+0x0): first defined here
```

**Comment by Lagrang3** [comment]
The culprit: a global variable `Parallel2d parallel;` declared in the header `LATfield2.hpp`.

**Comment by Lagrang3** [comment]
Global variables in libraries should be avoid as the plague. But if you don't have other choice then at least put then in a dedicated translation unit.

**Comment by Lagrang3** [comment]
I've pushed a [branch](https://github.com/Lagrang3/LATfield2/tree/liblatfield), to fix this issue. It is built on top of my master [branch](https://github.com/Lagrang3/LATfield2/tree/eduardo-master) because the fix requires to set up latfield as a binary library (no longer header-only) and thus automatic build rules become cumbersome with `makefile`, I used `meson` build-system which is lot more easier to use.

The main changes are:
- latfield is a header + linkable object library, ie. projects needs to link against `-llatfield`,
- classes implementations, global variables, global functions are all `cpp` files and will be compiled into a shared or static library file,
- a pkg-config file will be generated for eased use by the users.

**Comment by Lagrang3** [comment]
@daverio You can try building latfield library:
```
$ cd $SOURCE_PATH
$ git clone https://github.com/Lagrang3/LATfield2.git
$ git checkout liblatfield
$ mkdir build && cd build
$ meson --prefix=$INSTALL_PATH $SOURCE_PATH
$ meson install
```

**Comment by daverio** [comment]
Compability with existing code prevent to do this without refactoring some codes...
