### ISSUE TITLE
hdf5 version check

### ISSUE THREAD

**Issue by phychensong** [daverio/LATfield2#4]
Hi David

I have a error when using the newest version of HDF5. 
>>>>>>>>>>>>>>>>>>>> 
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.8.12, library is 1.8.18
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Best regards
Song

**Comment by JulianAdamek** [comment]
Dear Song,

this error actually indicates that you may have two different versions 
of HDF5 installed. Make sure your include path points to the same 
version as the one used by the linker.

Best wishes,
Julian

**Comment by daverio** [comment]
Hi Song,

Are you running on a cluster or on you own computer?
If it is a cluster I advise you to ask the system admin to solve this issues. if it is yours, you should set LD_LIBRARY_PATH to the correct directory, meaning the one the point to the same version as the headers.

Cheers,
David
On 16 Feb 2017, at 17:25, JulianAdamek <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Song,

this error actually indicates that you may have two different versions
of HDF5 installed. Make sure your include path points to the same
version as the one used by the linker.

Best wishes,
Julian
