### ISSUE TITLE
LATfield2 crashes

### ISSUE THREAD

**Issue by Lagrang3** [daverio/LATfield2#8]
The following innocent looking code crashes:

```
#define FFT3D
#include <fftw3.h>
#include "LATfield2.hpp"

using namespace LATfield2;

int main()
{
    const int n=2,m=2;
    const int BoxSize = 64 ;
    const int halo = 1;
    const int dim = 3;
    const int comp = 1;

    parallel.initialize(n,m);
    Lattice lat(dim,BoxSize,halo);
    Site x(lat);
    Field<Real> phi;
    phi.initialize(lat,comp);
    
    //Lattice latK;
    //latK.initializeRealFFT(lat, halo);
    //rKSite k(latK);
    //Field<Imag> phiK;
    //phiK.initialize(latK,comp);
    //
    //PlanFFT<Imag> planPhi(&phi,&phiK);

    for (x.first(); x.test(); x.next())
    {
        phi(x) = 1.0;
    }
}
```

However, it doesn't when the commented lines are uncommented.

This is the `makefile` used to compile:
```
default: main
LATFIELD:=../..

main : main.cpp
	g++ main.cpp -I${LATFIELD} `pkg-config --cflags --libs fftw3 ompi`
```

and it can be executed with 4 MPI processes:
```
$ mpirun -np 4 a.out
```

**Comment by Lagrang3** [comment]
@daverio I see that before using the `Field` class, the memory should be allocated by calling `alloc` method.
Is there any reason why not doing this inside the `initilize` method or within constructors?

Take for instance `std::vector` or `std::string`: you don't construct the object and then ask for allocation.
That's what constructors are for. This is the whole point of the C++ classes.

*The use of functions such as `init()` to provide initialization for class objects is inelegant and error-prone. Because it is nowhere stated that an object must be initialized, a programmer can forget to do so - or do so twice ... A better approach is to allow the programmer to declare a function with the explicit purpose of initializing objects ... [ie.] it is called a constructor.* Bjarne Stroustrup, The C++ Progamming Language section 16.2.5

*... A constructor's jobs is to initialize an object if its class. Often, that initialization must establish a class invariant, that is,
something that must hold whenever a member function is called ...* section 17.2.1

For example: a date object's invariant would be to represent internally a valid date, like 12th December 2012, and not 56th January year 0. 

The class `Field` in its current implementation, is allowed to be in a kind of dummy useless state from its default construction:
```
Field<Real> phi;
```
and even after manual initialization
```
 phi.initialize(lat,comp);
```
unless later on I call
```
phi.alloc();
```
And this is what triggers the segmentation fault that crashes the previous code.

Wouldn't it be nicer to have the constructor manage all these details under the hood?
```
Field<Real> phi(lat,comp);
// phi is ready to go
```

**Comment by daverio** [comment]
There is indeed a constructor 

Field<Real> phi(lat,...);

The split of initialize(...) and alloc(...) exist for a good reason. One might want to have 2 field which point to the same data, this is usefull for clarity of code and is widely used in some code based on latfield2 (gevolution for example)

So indeed, when a field is stored inside a class or a struct, one have to not forget to do the alloc(). Then when a PlanFFT is initialized, it alloc/realloc the linked fields, so when using FFT one does not need to perform the alloc() manually.

**Comment by Lagrang3** [comment]
@daverio Could you please reopen this issue? 
There might be a better way to provide the functionality that you want without need of the extra step `alloc()`.
