### ISSUE TITLE
Namespace pollution

### ISSUE THREAD

**Issue by Lagrang3** [daverio/LATfield2#9]
`LATfield2` is a header only library and it contains `using` directives all over.
Refer to Stroustrup's *The C++ Programming Language* 4th edition, Chapter 14 *Namespaces* and section 15.2.2 *Header Files*
as to why this is a bad practice.

This code for instance compiles:
```
#include <iostream>
#include "LATfield2.hpp"

int main()
{
    cout << "Namespace pollution\n";    
    return 0;
}
```
The user's namespace has been polluted without consent with `std`.

**Comment by daverio** [comment]
Indeed that is a bad feature of LATfield2, inerited from first version of LATfield...
Might be good to clean this!

**Comment by daverio** [comment]
Once again backward compabilities....
